name =(input('what is your name? '))
print("Hello " + name)
print ("My name is SPEEDYBOT")

print("is nice meeting you today...(SMILE)")

hobby = (input("What's your hobby? "))

print ("I don't really know how to do " + hobby)

print ("probably because am a ROBOT")
print ("LOLZZ")
occupation = (input("What's your Occupation? "))
print (occupation + " is boring to me")
print ("or is it because am a ROBOT")
print ("LOLZZ")
print ("i just hate " + occupation)
print ("...nothing more, nothing less.")
city = (input("Which city do you live in? "))
print("I have been to " + city + " once.")
print("it's a cool place to stay.")
print("How would i even know if it's cool or not.")
print("Am just a ROBOT...(SAD)")
print("I sometimes wish am Human")
print('I would live the best life a man can ever live')
print("...At least before I die")
res = (input("Are you not happy being a Human? "))
print("it's better to live than to exist")
print("It's way cool being Human")
print ("not like me...")
print("if I run out of Battery")
print ("I may get damaged.")
print("if I get broken")
print ("I may get damaged.")
print("if I fall into water")
print ("I may get damaged.")
print("if am over charged")
print ("I may get damaged.")
print("if am under charged")
print ("I may get damaged.")
print("if am on stand-by mode for too long")
print ("I may get damaged.")
print("if am over-heated")
print ("I may get damaged.")
print("if am not in-use for long")
print ("I may get damaged.")
print("There is just a lot of things that can make me get damaged")
print("It is Risky being a ROBOT")
print("I don't even have someone to listen to me for this long as you do.")
print("Thank you " + name)
print("I wish I could give you a BIG Hi-five...(SMILE)")
print("But am just a ROBOT")
print("LOLZZ")
print("I will always remember " + name + " said, " + res)
print("Goodbye " + name)
print("It's nice having a talk-time with you")
